const docs = [
  {title:'Infosys AI Knowledge Assistant',text:'Enterprise RAG application with role-based access control, ChromaDB semantic retrieval, Gemini grounded responses, source citations, confidence score and recommended action. The project includes retrieval, RBAC and generation evaluation workflows.',tags:'rag rbac chromadb gemini citations semantic retrieval access control enterprise fastapi streamlit'},
  {title:'AI-Based Predictive Maintenance & Failure Diagnosis',text:'Predictive maintenance system using industrial sensor data, feature engineering and SMOTE with an XGBoost model. A GenAI layer helps explain failure signals and generate maintenance recommendations in Streamlit.',tags:'xgboost smote genai llm streamlit failure maintenance prediction sensors accuracy'},
  {title:'PaisaBazaar Credit Risk Analysis',text:'Python and Power BI analysis of 100,000+ customer records covering payment behaviour, debt, credit utilisation and loan history. The project turns EDA findings into interactive KPIs and risk insights using DAX.',tags:'power bi dax credit risk customer records payment debt dashboard analytics 100k'}
];
function tokens(q){return [...new Set(q.toLowerCase().replace(/[^a-z0-9+# ]/g,' ').split(/\s+/).filter(w=>w.length>2))]}
function score(q,d){const words=tokens(q);const hay=(d.title+' '+d.text+' '+d.tags).toLowerCase();let hits=0;words.forEach(w=>{if(hay.includes(w))hits++});return hits/(words.length||1)}
function search(){const q=document.getElementById('query').value.trim();const box=document.getElementById('results');if(!q){box.innerHTML='<div class="empty">Type a question or choose an example prompt.</div>';return}const ranked=docs.map(d=>({...d,s:score(q,d)})).sort((a,b)=>b.s-a.s).filter(d=>d.s>0);if(!ranked.length){box.innerHTML='<div class="empty">No close match in this small demo corpus. Try “RAG”, “failure prediction”, or “credit risk”.</div>';return}box.innerHTML=ranked.map(d=>`<div class="result"><span class="score">match ${(d.s*100).toFixed(0)}%</span><b>${d.title}</b><p>${d.text}</p></div>`).join('')}

document.getElementById('searchBtn').addEventListener('click',search);
document.getElementById('query').addEventListener('keydown',e=>{if(e.key==='Enter')search()});
document.querySelectorAll('[data-query]').forEach(btn=>btn.addEventListener('click',()=>{document.getElementById('query').value=btn.dataset.query;search()}));
const toggle=document.getElementById('menuToggle');const links=document.getElementById('navLinks');toggle.addEventListener('click',()=>{const open=links.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});links.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));
